### ISSUE TITLE
AttributeError at /admin/login/ 'MetaDict' object has no attribute 'pk'

### ISSUE THREAD

**Issue by xycfree** [BurkovBA/django-rest-framework-mongoengine-example#11]
Request Method: | POST
-- | --
http://127.0.0.1:8007/admin/login/?next=/admin/
1.9
AttributeError
'MetaDict' object has no attribute 'pk'
D:\tools\python36\venv2\lib\site-packages\django\contrib\auth\__init__.py in login, line 111
D:\tools\python36\venv2\Scripts\python3.6.exe
3.6.5

**Comment by xycfree** [comment]
[29/Aug/2018 19:32:28] "POST /api/auth/ HTTP/1.1" 200 6639
[29/Aug/2018 19:34:20] "GET /admin/ HTTP/1.1" 302 0
[29/Aug/2018 19:34:20] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1679
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\tools\python36\venv2\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\tools\python36\venv2\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\tools\python36\venv2\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\tools\python36\venv2\lib\site-packages\django\contrib\admin\sites.py", line 407, in login
    return login(request, **defaults)
  File "D:\tools\python36\venv2\lib\site-packages\django\contrib\auth\views.py", line 49, in inner
    return func(*args, **kwargs)
  File "D:\tools\python36\venv2\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\tools\python36\venv2\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\tools\python36\venv2\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\tools\python36\venv2\lib\site-packages\django\contrib\auth\views.py", line 76, in login
    auth_login(request, form.get_user())
  File "D:\tools\python36\venv2\lib\site-packages\django\contrib\auth\__init__.py", line 111, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
AttributeError: 'MetaDict' object has no attribute 'pk'
[29/Aug/2018 19:34:31] "POST /admin/login/?next=/admin/ HTTP/1.1" 500 104218
